name: Trigger auto deployment for demo-fastapi-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/demo-fastapi-app-AutoDeployTrigger-e7e22ab0-bd2a-4926-9d51-822c8d4fc6c0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEMOFASTAPIAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEMOFASTAPIAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEMOFASTAPIAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.DEMOFASTAPIAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEMOFASTAPIAPP_REGISTRY_PASSWORD }}
          containerAppName: demo-fastapi-app
          resourceGroup: MyProjects
          imageToBuild: p1utoze/demo-fastapi-app:${{ github.sha }}
          


