name: Trigger auto deployment for fastapi-demo-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fastapi-demo-app-AutoDeployTrigger-7bdd569e-7044-4188-b3b1-e08f84465293.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FASTAPIDEMOAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FASTAPIDEMOAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FASTAPIDEMOAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.FASTAPIDEMOAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FASTAPIDEMOAPP_REGISTRY_PASSWORD }}
          containerAppName: fastapi-demo-app
          resourceGroup: MyProjects
          imageToBuild: p1utoze/fastapi-demo-app:${{ github.sha }}
          


